apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ace-parent
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/mfarhanSystemsltd/argocd-test.git
        revision: HEAD
        files:
        - path: "ACE/argocd/**/config.json"
  template:
    metadata:
      name: 'parent-{{namespace}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/mfarhanSystemsltd/argocd-test.git
        targetRevision: HEAD
        path: "ACE/argocd/{{namespace}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
