apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: oms-ace-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/mfarhanSystemsltd/argocd-test.git
        revision: HEAD
        files:
        - path: "ACE/**/overlays/**/config.json"
  template:
    metadata:
      name: '{{microservice}}-{{namespace}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/mfarhanSystemsltd/argocd-test.git
        targetRevision: HEAD
        path: "ACE/{{microservice}}/overlays/{{namespace}}/"
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
